function [WX,W] = ILAD(y,X,h)
[WX0, W0]=ldr(y,X,'lad','cont',1,'nslices',5);
bx=X*W0;
bxx=bx.^2;
B = [ones(length(bx),1) bx bxx]\X;
X=X-[ones(length(bx),1) bxx]*B([1 3],:);
[WX0, W0]=ldr(y,X,'lad','cont',1,'nslices',5);
bx=X*W0;
bxx=bx.^2;
B = [ones(length(bx),1) bx bxx]\X;
X=X-[ones(length(bx),1) bxx]*B([1 3],:);
[WX0, W0]=ldr(y,X,'lad','cont',1,'nslices',5);
bx=X*W0;
bxx=bx.^2;
B = [ones(length(bx),1) bx bxx]\X;
X=X-[ones(length(bx),1) bxx]*B([1 3],:);
[WX0, W0]=ldr(y,X,'lad','cont',1,'nslices',5);
bx=X*W0;
bxx=bx.^2;
B = [ones(length(bx),1) bx bxx]\X;
X=X-[ones(length(bx),1) bxx]*B([1 3],:);
[WX0, W0]=ldr(y,X,'lad','cont',1,'nslices',5);
bx=X*W0;
bxx=bx.^2;
B = [ones(length(bx),1) bx bxx]\X;
X=X-[ones(length(bx),1) bxx]*B([1 3],:);
[WX, W]=ldr(y,X,'lad','cont',1,'nslices',5);

